//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTWCHARLIEKODE
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails
    {
        public int DetailId { get; set; }
        public int InvoiceId { get; set; }
        public int PackageId { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual Packages Packages { get; set; }
    }
}
